language: node_js
node_js:
  - "0.10"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y -qq install wget libssl0.9.8
  - sudo wget -q http://packages.couchbase.com/releases/2.0.1/couchbase-server-enterprise_x86_64_2.0.1.deb -O couchbase-server.deb
  - sudo dpkg -i couchbase-server.deb